### ISSUE TITLE
locus_def failing with v0.24.0

### ISSUE THREAD

**Issue by anneliedm** [davidlougheed/strkit#14]
Hello,

I've been encountering this issue since the 0.24.0 version update of strkit (which does improve the visualization tool):

`strkit-main:    [ERROR] [w1] locus 1 (id=locus1): chr1:57367043-57367125 [RAAAT] - encountered exception while genotyping (locus.n_alleles=2): AttributeError("'builtins.STRkitLocusWithRefData' object has no attribute 'locus_def'")
strkit-main:    [ERROR] [w1] locus 1 (id=locus1): chr1:57367043-57367125 [RAAAT] - Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/strkit/call/call_sample.py", line 166, in locus_worker
    res = call_locus(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/strkit/call/call_locus.py", line 1017, in call_locus
    pairs_new = perform_realign(locus_with_ref_data, segment, params, logger_, locus_log_str)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/strkit/call/realign.py", line 87, in perform_realign
    left_flank_coord = locus_with_ref_data.locus_def.left_flank_coord
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtins.STRkitLocusWithRefData' object has no attribute 'locus_def'`

This error happens for multiple loci. I have tried running instances both locally as well as on Compute Canada and get the same results. I've also tested multiple samples and the loci with errors aren't consistent amongst the samples. However, I've confirmed that these loci have multiple reads, and that they work with v0.22.0. Just thought I'd detail this issue in case I'm not the only one having it.

Thanks for your time!

**Comment by davidlougheed** [comment]
@anneliedm sorry for the slow response on this; I've added instructions on how to remotely access the visualization tool - see https://github.com/davidlougheed/strkit/blob/master/docs/remote_viz.md 

Do note that because of how this works, technically others can access the tool while you're signed in and runnin git. There may be a way to secure this in the future, but that would be a bigger task.

**Comment by anneliedm** [comment]
Thanks so much!
